# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20160119_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('test_number', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'UnidadMedidas',
                'verbose_name': 'UnidadMedida',
            },
        ),
    ]
